plugins {
    id "idea"
    id "eclipse"
    id "maven-publish"
    id "net.minecraftforge.gradle" version "[6.0,6.2)"
    id "org.parchmentmc.librarian.forgegradle" version "1.+"
}

version = mod_version
group = mod_group

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

jarJar.enable()

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {

    mappings channel: "parchment", version: "${parchment_version}-${parchment_minecraft_version}"
    copyIdeResources = true
    accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg")

    runs {
        configureEach {
            workingDirectory project.file("run")
        }
        client {
            property "forge.logging.markers", "REGISTRIES"
            property "forge.logging.console.level", "info"
            property "forge.enabledGameTestNamespaces", mod_id

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        server {
            property "forge.logging.markers", "REGISTRIES"
            property "forge.logging.console.level", "info"
            property "forge.enabledGameTestNamespaces", mod_id

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        gameTestServer {
            property "forge.logging.markers", "REGISTRIES"
            property "forge.logging.console.level", "info"
            property "forge.enabledGameTestNamespaces", mod_id

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        data {
            property "forge.logging.markers", "REGISTRIES"
            property "forge.logging.console.level", "info"
            args "--mod", "${mod_id}", "--all", "--output", file("src/generated/resources/"), "--existing", file("src/main/resources/")

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir "src/generated/resources" }

repositories {
    maven {
        name = "Commoble's Maven"
        url = "https://maven.commoble.net/"
    }

    maven { // JEI is now hosted here as dvs1.progwm16.com has retired.
        name = "BlameJared Maven"
        url = "https://maven.blamejared.com"
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"

    implementation fg.deobf("commoble.infiniverse:${infiniverse_github_branch}:${infiniverse_version}")
    jarJar(group: "commoble.infiniverse", name: "${infiniverse_github_branch}", version: "[${infiniverse_version}, ${infiniverse_max_version})")

    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
}

tasks.named("processResources", ProcessResources).configure {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_issue_tracker      : mod_issue_tracker,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]

    inputs.properties replaceProperties
    filesMatching(["META-INF/mods.toml"]) {
        expand replaceProperties + [project: project]
    }
}

tasks.named("jarJar") {

}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "${mod_id}",
                "Specification-Vendor"    : "${mod_authors}",
                "Specification-Version"   : "1",
                "Implementation-Title"    : "${mod_name}",
                "Implementation-Version"  : "${mod_version}",
                "Implementation-Vendor"   : "${mod_authors}",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    finalizedBy "reobfJar"
}

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register("mavenJava", MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation
}