# Minecraft properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,)

# Mod properties
mod_name=Nomadic Tents
mod_id=nomadictents
mod_version=20.1.1
mod_authors=skyjay1
mod_description=Yurts, Tepees and other portable houses!
mod_issue_tracker=https://github.com/skyjay1/Nomadic-Tents
mod_group=skyjay1.nomadictents
mod_license=GNU General Public License v3

# Forge
forge_version=47.3.25
forge_version_range=[47.3,)
loader_version_range=[47,)

# Mappings
# See https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft_version=1.20.1
parchment_version=2023.09.03

# Mod Dependencies
infiniverse_github_branch=infiniverse-1.20.1
infiniverse_version=1.0.0.5
# Max version required because apparently Jar in Jar doesn't support setting one version or "version+" for non-existent future versions
infiniverse_max_version=2.0.0.0
jei_version=15.19.5.99

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false