package com.yurtmod.main;

import net.minecraftforge.common.config.Configuration;

public class Config {
	public static boolean SUPER_MALLET_CREATIVE_ONLY;
	public static boolean ALLOW_YURT;
	public static boolean ALLOW_TEPEE;
	public static boolean ALLOW_BEDOUIN;
	public static boolean ALLOW_INDLU;
	
	public static boolean ALLOW_PLAYER_COLLIDE;
	public static boolean ALLOW_NONPLAYER_COLLIDE;
	public static int TEPEE_DECORATED_CHANCE;

	public static boolean ALLOW_SLEEP_TENT_DIM;
	public static boolean ALLOW_TELEPORT_TENT_DIM;
	public static boolean ALLOW_RESPAWN_INTERCEPT;

	public static boolean IS_TENT_FIREPROOF; // TODO

	public static boolean REQUIRE_MORE_CANVAS;
	public static boolean REQUIRE_MORE_LEATHER;
	public static boolean REQUIRE_CARPET;
	public static int NUM_YURT_WALL_OUTPUT;
	public static int NUM_TEPEE_WALL_OUTPUT;
	public static int NUM_TEPEE_WALL_OUTPUT_RABBIT;
	public static int NUM_BED_WALL_OUTPUT;
	public static int NUM_INDLU_WALL_OUTPUT;

	public static boolean REQUIRE_GOLD_BLOCKS;
	public static int DIMENSION_ID;


	private static final String C_TEPEE_WALL = "tepee_wall_piece";
	private static final String C_YURT_WALL = "yurt_wall_piece";
	private static final String C_BED_WALL = "bedouin_wall_piece";
	private static final String C_INDLU_WALL = "indlu_wall_piece";
	private static final String CATEGORY_CRAFTING = "crafting";

	public static void mainRegistry(Configuration config) {
		config.load();

		ALLOW_YURT = config.getBoolean("Enable Yurt", CATEGORY_CRAFTING, true,
				"Whether the Yurt can be built and used");
		ALLOW_TEPEE = config.getBoolean("Enable Tepee", CATEGORY_CRAFTING, true,
				"Whether the Tepee can be built and used");
		ALLOW_BEDOUIN = config.getBoolean("Enable Bedouin", CATEGORY_CRAFTING, true,
				"Whether the Bedouin can be built and used");
		ALLOW_INDLU = config.getBoolean("Enable Indlu", CATEGORY_CRAFTING, true,
				"Whether the Indlu can be built and used");
		REQUIRE_GOLD_BLOCKS = config.getBoolean("Use Gold Blocks for Super Mallet", CATEGORY_CRAFTING, false,
				"When true, the Super Tent Mallet recipe will use gold blocks instead of enchanted golden apples");

		REQUIRE_MORE_CANVAS = config.getBoolean("Require More Canvas", C_YURT_WALL, false,
				"When true, the Yurt Wall recipe requires 6 canvas instead of 4");
		NUM_YURT_WALL_OUTPUT = config.getInt("Recipe Output Amount", C_YURT_WALL, 1, 1, 6,
				"Number of Yurt Wall Pieces generated by one recipe");
		REQUIRE_MORE_LEATHER = config.getBoolean("Require More Leather", C_TEPEE_WALL, false,
				"When true, the Tepee Wall recipe requires 6 leather instead of 4");
		NUM_TEPEE_WALL_OUTPUT = config.getInt("Recipe Output Amount", C_TEPEE_WALL, 1, 1, 6,
				"Number of Tepee Wall Pieces generated by one recipe");

		REQUIRE_CARPET = config.getBoolean("Require Carpet", C_BED_WALL, false,
				"When true, the Bedouin Wall recipe requires 4 carpet instead of 4 wool");
		NUM_BED_WALL_OUTPUT = config.getInt("Recipe Output Amount", C_BED_WALL, 1, 1, 6,
				"Number of Bedouin Wall Pieces generated by one recipe");
		
		NUM_INDLU_WALL_OUTPUT = config.getInt("Recipe Output Amount", C_INDLU_WALL, 1, 1, 6,
				"Number of Indlu Wall Pieces generated by one recipe");

		SUPER_MALLET_CREATIVE_ONLY = config.getBoolean("Super Mallet Creative-Only", Configuration.CATEGORY_GENERAL, false,
				"When true, only Creative-mode players can use the Super Mallet");
		DIMENSION_ID = config.getInt("Tent Dimension ID", Configuration.CATEGORY_GENERAL, 68, -9999, 9999,
				"The ID for the Tent Dimension. (Warning: changing this will reset all tents!)");
		TEPEE_DECORATED_CHANCE = config.getInt("Tepee Design Chance", Configuration.CATEGORY_GENERAL, 35, 0, 100,
				"Percent chance that blank tepee wall will have design (does not affect horizontal patterns)");
		ALLOW_SLEEP_TENT_DIM = !config.getBoolean("Beds explode in Tent Dim", Configuration.CATEGORY_GENERAL, false,
				"When true, beds used in the Tent Dimension will explode and players can't sleep there");
		
		ALLOW_PLAYER_COLLIDE = config.getBoolean("Allow Player Walk-In", Configuration.CATEGORY_GENERAL, true,
				"[Experimental] When true, players can enter the tent by walking through the door");
		ALLOW_NONPLAYER_COLLIDE = config.getBoolean("Allow Entity Walk-In", Configuration.CATEGORY_GENERAL, false,
				"[Experimental] When true, non-player entities can enter the tent by walking through the door");
		ALLOW_RESPAWN_INTERCEPT = config.getBoolean("Allow Respawn Logic", Configuration.CATEGORY_GENERAL, true,
				"When true, players who die in Tent Dimension will be sent to overworld IF they have no bed. Disable if buggy.");
		//IS_TENT_FIREPROOF = config.getBoolean("Is Tent Fireproof", Configuration.CATEGORY_GENERAL, false,
		//		"When true, the tent item will not be destroyed if it is burned");

		config.save();
	}
}
